"""Added Departments table

Revision ID: 52fecea5921a
Revises: 62b0071f054c
Create Date: 2024-06-19 07:28:22.026530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fecea5921a'
down_revision: Union[str, None] = '62b0071f054c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('imageLink', sa.String(length=128), nullable=False),
    sa.Column('quantityOfWorkers', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], name=op.f('fk_departments_user_uuid_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###
