"""Init

Revision ID: 76759ac3d36d
Revises: 
Create Date: 2024-03-12 23:06:12.635454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76759ac3d36d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies')),
    sa.UniqueConstraint('code', name=op.f('uq_currencies_code')),
    sa.UniqueConstraint('name', name=op.f('uq_currencies_name')),
    sa.UniqueConstraint('symbol', name=op.f('uq_currencies_symbol'))
    )
    op.create_table('transactions_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions_types')),
    sa.UniqueConstraint('name', name=op.f('uq_transactions_types_name'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('fk_accounts_currency_id_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_table('transactions_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['transactions_types.id'], name=op.f('fk_transactions_categories_type_id_transactions_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_transactions_categories_name'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('datetime_updated', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts')),
    sa.ForeignKeyConstraint(['category_id'], ['transactions_categories.id'], name=op.f('fk_transactions_category_id_transactions_categories')),
    sa.ForeignKeyConstraint(['type_id'], ['transactions_types.id'], name=op.f('fk_transactions_type_id_transactions_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('transactions_categories')
    op.drop_table('accounts')
    op.drop_table('transactions_types')
    op.drop_table('currencies')
    # ### end Alembic commands ###
