"""Make links between user and accounts

Revision ID: 94697308060e
Revises: 1d825973960b
Create Date: 2024-05-07 04:33:40.965541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94697308060e'
down_revision: Union[str, None] = '1d825973960b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_uuid', sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f('fk_accounts_user_uuid_users'), 'accounts', 'users', ['user_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_accounts_user_uuid_users'), 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user_uuid')
    # ### end Alembic commands ###
